FileVersion = 1

[Project]
Name = "librg-beef"
DefaultNamespace = "librg"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\librg_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\librg.lib"]
